package com.devop.JobApp.company;
import com.devop.JobApp.job.Job;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import com.devop.JobApp.reviews.Review;
import java.util.List;

@Entity//It's any entity
public class Company {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;//It acts as a primary key where it is automatically generated by spring framework
    private String name;//Company Name
    private String description;//Description of the Company
    @JsonIgnore//It is used to ignore the object from SerDe
    @OneToMany(mappedBy = "company")//One Company is Mapped To Many Jobs based on company field
    private List<Job> jobs;

    @JsonIgnore
    @OneToMany(mappedBy = "company")//One Company is Mapped To Many Reviews based on company field
    private List<Review> reviews;
    public Company() {

    }

    public List<Review> getReviews() {
        return reviews;
    }

    public void setReviews(List<Review> reviews) {
        this.reviews = reviews;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<Job> getJobs() {
        return jobs;
    }

    public void setJobs(List<Job> jobs) {
        this.jobs = jobs;
    }
}
